[build]
  command = "yarn build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "https://gxanshu.in"
  status = 301
  force = true

[[redirects]]
  from = "https://codenanshu.in/*"
  to = "https://gxanshu.in/:splat"
  status = 301
  force = true